spring:
  application:
    name: gateway

eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/