services:
  calculator:
    name: calculator
  deal:
    name: deal
  statement:
    name: statement
  dossier:
    name: dossier

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: rewrite_to_statement_api_get_loan
          uri: lb://${services.statement.name}
          predicates:
            - Query=typePayment
            - Method=POST
            - Path=/api/statement
          filters:
            - RewritePath=/api/statement(?<segment>), /v1/statement${segment}

        - id: rewrite_to_statement_api_select_loan
          uri: lb://${services.statement.name}
          predicates:
            - Query=typePayment
            - Method=POST
            - Path=/api/statement/select
          filters:
            - RewritePath=/api/statement/select(?<segment>), /v1/statement/offer${segment}

        - id: rewrite_to_deal_api_calculate_credit
          uri: lb://${services.deal.name}
          predicates:
            - Method=POST
            - Path=/api/statement/registration/**
          filters:
            - RewritePath=/api/statement/registration/(?<segment>.*), /v1/deal/calculate/$\{segment}

        - id: rewrite_to_deal_api_documents
          uri: lb://${services.deal.name}
          predicates:
            - Path=/api/document/(?<segment>)/**
          filters:
            - RewritePath=/api/document/(?<segment>.*)/**, /v1/deal/document/$\{segment}/**

        - id: rewrite_to_deal_api_admin
          uri: lb://${services.deal.name}
          predicates:
            - Path=/api/admin/statement
          filters:
            - RewritePath=/api/admin/statement/(?<segment>.*), /v1/deal/admin/statement/$\{segment}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

springdoc:
  swagger-ui:
    path: /openapi/api-docs-ui

eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/