spring:
  application:
    name: gateway

springdoc:
  api-docs:
    path: /openapi/api-docs
  swagger-ui:
    path: /openapi/api-docs-ui

eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/