spring:
  config:
    import: email-config.yml
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group-id: deal-notifications
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'



kafka:
  init:
    topics: true
  topics:
    finish_registration: finish-registration
    create_documents: create-documents
    send_documents: send-documents
    send_ses: send-ses
    credit_issued: credit-issued
    statement_denied: statement-denied