spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: msunchalyaev@gmail.com
    password: cmbkwsytntwiklev
    protocol: smtps
    properties:
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true