spring:
  application:
    name: deal
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-main.xml
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:8088/deal_db
    driver-class-name: org.postgresql.Driver
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

kafka:
  init:
    topics: true
  topics:
    finish_registration: finish-registration
    create_documents: create-documents
    send_documents: send-documents
    send_ses: send-ses
    credit_issued: credit-issued
    statement_denied: statement-denied

springdoc:
  api-docs:
    path: /api-doc
  swagger-ui:
    path: /api-docs-ui

clients:
  calculator:
    name: calculator

logging:
  level:
    root: info