name: continue integration calculator

on:
  pull_request:
    branches:
      - dev/calculator
  push:
    branches:
      - dev/calculator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   path: BankService/Calculator

      - name: Set up to JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=MunSunch_BankService -Dsonar.organization=munsunch -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
        working-directory: BankService/Calculator


      - name: Test Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: DockerHub Authenticate
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract project version for docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/calculator:$VERSION .
        working-directory: BankService/Calculator

      - name: Send to dockerhub registry
        run: docker push ${{ secrets.DOCKER_LOGIN }}/calculator:$VERSION