name: continue integration dossier

on:
  push: 
    branches:
      - dev/dossier
  pull_request:
    branches:
      - dev/dossier

env:
  DIRECTORY: BankService/Dossier
  PROJECT: dossier

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up to JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: Set environment with docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ${{ env.DIRECTORY }}/docker-compose.yml

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B clean verify 
          -DMAIL_HOST=${{ secrets.MAIL_HOST }}
          -DMAIL_PORT=${{ secrets.MAIL_PORT }} 
          -DMAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
          -DMAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          -DMAIL_PROTOCOL=${{ secrets.MAIL_PROTOCOL }} 
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=MunSunch_BankService -Dsonar.organization=munsunch -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.coverage.jacoco.xmlReportPaths=./target/site/jacoco/jacoco.xml
        working-directory: ${{ env.DIRECTORY }}

      - name: Test Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: DockerHub Authenticate
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract project version for docker image
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          RELEASE_VERSION=$(echo $VERSION | sed 's/-SNAPSHOT//')
          echo "VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
        working-directory: ${{ env.DIRECTORY }}

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT }}:$VERSION .
        working-directory: ${{ env.DIRECTORY }}

      - name: Send to dockerhub registry
        run: docker push ${{ secrets.DOCKER_LOGIN }}/${{ env.PROJECT }}:$VERSION