spring:
  application:
    name: statement

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/

clients:
  deal:
    name: deal

springdoc:
  swagger-ui:
    path: /openapi/ui-docs
  api-docs:
    path: /openapi/docs